### ISSUE TITLE
关于angdiff函数

### ISSUE THREAD

**Issue by Gxer** [meyiao/LaserSLAM#1]

**Comment by meyiao** [comment]
angdiff是matlab自带的函数, 用来求角度的差。如果你用的的matlab版本没有这个函数的话，可以自己写一个。

%
function d = angdiff(a, b)

d = (b - a) ;

% constrain d in [0, 2*pi]
two_pi = 2 * pi;
d = d - floor(d/two_pi)*two_pi;

% constrain d in [-pi, pi]
if d > pi
     d = d - two_pi;
end













2017-06-01 10:59 GMT+08:00 Gxer <notifications@github.com>:
