### ISSUE TITLE
想问一下SetLidarParameters里面参数是依据什么设置的？

### ISSUE THREAD

**Issue by roachsinai** [meyiao/LaserSLAM#4]
还有，麻烦能不能给一些`Deutsches Museum`数据格式说明，[ Cartographer ROS data](https://google-cartographer-ros.readthedocs.io/en/latest/data.html#data)只有：

Duration | Size | Floor
-- | -- | --

**Comment by meyiao** [comment]
下载一个bag包, 通过rosbag info, rsomsg show, rostopic echo 等命令可以查看。
rosmsg show sensor_msgs/MultiEchoLaserScan
